name: Test the RLtools Python Interface Using Conda

on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04, macos-latest]
        mkl: [no, yes]
        python-version: ["3.12", "3.11", "3.10", "3.9", "3.8"] # conda does not support 3.7 anymore
        exclude:
          - os: macos-latest
            mkl: yes
    steps:
    - uses: actions/checkout@v3
    - uses: conda-incubator/setup-miniconda@v3.0.3
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}

    - name: Checkout External Submodules
      run: |
        git submodule update --init -- rltools/external/rl_tools

    - name: Update pip
      run: |
        pip install --upgrade pip

    - name: Install package
      if: matrix.mkl == 'no'
      run: |
        pip install -e .[tests]
    - name: Install package
      if: matrix.mkl == 'yes'
      run: |
        pip install -e .[mkl,tests]
    - name: Install test dependencies
      run: |
        pip install gymnasium pytest
        
    - name: Test with pytest
      if: matrix.mkl == 'no'
      env:
        RL_TOOLS_FORCE_RECOMPILE: ""
        RL_TOOLS_FORCE_COMPILE_VERBOSE: ""
        RL_TOOLS_DISABLE_PYTORCH_IMPORT_TEST: ""
      run: |
        pytest tests -s
    - name: Test with pytest (force MKL)
      if: matrix.mkl == 'yes'
      env: 
        RL_TOOLS_FORCE_MKL: 1
        RL_TOOLS_DISABLE_PYTORCH_IMPORT_TEST: ""
      run: |
        pytest tests -s
