name: Test PyRLtools using pip

on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04, macos-latest]
        mkl: [no, yes]
        python-version: ["3.12", "3.11", "3.10", "3.9", "3.8", "3.7"]
        exclude:
          - os: macos-latest
            mkl: yes
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Checkout External Submodules
      run: |
        git submodule update --init -- pyrltools/external/rl_tools

    - name: Update pip
      run: |
        pip install --upgrade pip

    - name: Install package
      if: matrix.mkl == 'no'
      run: |
        pip install -e .[tests]
    - name: Install package
      if: matrix.mkl == 'yes'
      run: |
        pip install -e .[mkl,tests]
    - name: Install test dependencies
      run: |
        pip install gymnasium pytest
        
    - name: Test with pytest
      if: matrix.mkl == 'no'
      env:
        PYRLTOOLS_FORCE_RECOMPILE: ""
        PYRLTOOLS_FORCE_COMPILE_VERBOSE: ""
        PYRLTOOLS_DISABLE_PYTORCH_IMPORT_TEST: ""
      run: |
        pytest tests -s
    - name: Test with pytest (force MKL)
      if: matrix.mkl == 'yes'
      env: 
        PYRLTOOLS_FORCE_MKL: 1
        PYRLTOOLS_DISABLE_PYTORCH_IMPORT_TEST: ""
      run: |
        pytest tests -s
