name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Checkout External Submodules
      run: |
        git submodule update --init -- tinyrl/external/rl_tools


    - name: Installing Minimal Dependencies
      if: startsWith(matrix.os, 'ubuntu')
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential ninja-build
    - name: Installing Minimal Dependencies
      if: startsWith(matrix.os, 'macos')
      run: |
        brew install ninja

    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH

    - name: Install package
      run: |
        pip install -e .${{ matrix.c_compiler }}
    # - name: Install dependencies
    #   run: |
    #     conda env update --file environment.yml --name base
    # - name: Lint with flake8
    #   run: |
    #     conda install flake8
    #     # stop the build if there are Python syntax errors or undefined names
    #     flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    #     # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
    #     flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Install test dependencies
      run: |
        pip install gymnasium
    - name: Test with pytest
      run: |
        conda install pytest
        pytest tests
    - name: Test with pytest (force MKL)
      env: 
        TINYRL_FORCE_MKL: 1
      run: |
        conda install pytest
        pytest tests
